# environment: "local"

# http_server:
#   address: "127.0.0.1"
#   port: 4000

# storage:
#   type: "postgres"
#   postgres:
#     host: "127.0.0.1"
#     port: 5432
#     username: "postgres"
#     password: "postgres"
#     db_name: "comments"

environment: "local"

http_server:
  address: "127.0.0.1"
  port: 4000

storage:
  type: "memory"