// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Content          string     `json:"content"`
	CommentsDisabled bool       `json:"commentsDisabled"`
	CreatedAt        string     `json:"createdAt"`
	Comments         []*Comment `json:"comments"`
}

type Query struct {
}
